### ISSUE TITLE
[FR] Code Owner Commands for Dependency Labels

### ISSUE THREAD

**Issue by shbatm** [home-assistant/service-hub#133]
The code owner commands are awesome, thanks. 

Wanted to suggest adding one to add the `Problem in Dependency` label for issues that need upstream fixes before progressing. 

(May not be the best place to discuss, please close if not).

**Comment by frenck** [comment]
I like that suggestion 👍

**Comment by ludeeus** [comment]
I do not like it, it's too specific.

`/add-label [label]` and `/remove-label [label]` with an allowlist of labels that can be managed would be good 👍

**Comment by frenck** [comment]
Yeah, sure, that is similar enough and more flexible 👍

**Comment by shbatm** [comment]
Works for me!
