### ISSUE TITLE
CLA Bot - Issue with Regions

### ISSUE THREAD

**Issue by psuet** [home-assistant/service-hub#136]
When trying to "sign" the CLA at this [endpoint](https://service-hub-bots.home-assistant.io/cla-sign) with the following request data

```{"country":"Germany","email":"[...]","name":"[...]","github_username":"psuet","region":"Hessen","signing_for":"self","i_agree":"on","github_user_id":"7604288","pull_request":"home-assistant/supervised-installer#259"}```

I recieved multiple Internal Server Errors (500). Once I removed my region and selected "Select State" in the [form](https://www.home-assistant.io/developers/cla_sign/) it worked.

**Comment by ludeeus** [comment]
Looked at the logs, all your requests that failed was missing `pull_request`, you get that when you just go to the page outside the provided link.
